title: Cami Carballo
email: ccarball@nd.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "camicarballo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  camicarballo

# Build settings
theme: jekyll-theme-hacker
plugins:

